### ISSUE TITLE
StatusBar color disabled 

### ISSUE THREAD

**Issue by nalmada** [palaima/DebugDrawer#1]
On Android 5.1.1 (Nexus 5)
Using io.palaima.debugdrawer:debugdrawer:0.1.1

The StatusBar color is disabled 

Here's my code : 

```java 
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        ButterKnife.inject(this);
        stock();
        if (BuildConfig.DEBUG) {

            mDebugDrawer = new DebugDrawer.Builder(this).modules(
                    new DeviceModule(this),
                    new BuildModule(this),
                    new NetworkModule(this),
                    new SettingsModule(this)
            ).build();
        }
    }

@Override
    protected void onStart() {
        super.onStart();
        if (mDebugDrawer != null) {
            mDebugDrawer.onStart();
        }
    }

    @Override
    protected void onStop() {
        super.onStop();
        if (mDebugDrawer != null) {
            mDebugDrawer.onStop();
        }
    }
```

The issue seems to be in the my stock() function where i'm setting an ```android.support.v7.widget.Toolbar ```. If i remove the toolbar everything is fixed.

Thanks,

**Comment by vvasanth86** [comment]
+1

**Comment by palaima** [comment]
Thanks for report.
I'll try to dig what causes this problem

**Comment by palaima** [comment]
Check demo app. I have changed actionbar with toolbar. Status bar color is changed to colorPrimaryDark and is not disabled. Also tried change status bar color programmatically (See MainActivity.java), works fine.

**Comment by nalmada** [comment]
After checking again , the issue happens because i also use the com.mikepenz.materialdrawer library for my main navig drawer
Will try with an other lib

**Comment by vvasanth86** [comment]
Same here. I'm using `com.mikepenz.materialdrawer` too. Let me know if you find a solution.

Thanks!

**Comment by vvasanth86** [comment]
@nalmada  FYI, I set `com.mikepenz.materialdrawer`'s Drawer with `.withTranslucentStatusBar(false)` and that resolved the problem for me. Hope it helps!

**Comment by nalmada** [comment]
Yes it works (even if then the nav drawer doesn't follow material design guidelines).
Thanks anyway.
