### ISSUE TITLE
I am maintaining a fork of DebugDrawer

### ISSUE THREAD

**Issue by lenguyenthanh** [palaima/DebugDrawer#103]
So this great library was not maintained for almost two years. So I decided to fork it and continue to maintain it here: [lenguyenthanh/DebugDrawer](https://github.com/lenguyenthanh/DebugDrawer).

I have done:
- Upgrade Androidx and other dependencies
- Fix #78

I published it to `https://jitpack.io/#lenguyenthanh/debugdrawer` so anyone can use that. Here is an example:

```
    debugImplementation "com.github.lenguyenthanh.debugdrawer:debugdrawer-base:0.9.0"
    debugImplementation "com.github.lenguyenthanh.debugdrawer:debugdrawer:0.9.0"
    debugImplementation "com.github.lenguyenthanh.debugdrawer:debugdrawer-view:0.9.0"
    debugImplementation "com.github.lenguyenthanh.debugdrawer:debugdrawer-okhttp3:0.9.0"
    debugImplementation "com.github.lenguyenthanh.debugdrawer:debugdrawer-scalpel:0.9.0"
    debugImplementation "com.github.lenguyenthanh.debugdrawer:debugdrawer-picasso:0.9.0"
    debugImplementation "com.github.lenguyenthanh.debugdrawer:debugdrawer-timber:0.9.0"
    debugImplementation "com.github.lenguyenthanh.debugdrawer:debugdrawer-fps:0.9.0"
    debugImplementation "com.github.lenguyenthanh.debugdrawer:debugdrawer-actions:0.9.0"
    debugImplementation "com.github.lenguyenthanh.debugdrawer:debugdrawer-commons:0.9.0"
```

Welcome to any PR or issues in my repository.

**Comment by eric-labelle** [comment]
Any plans to convert the library to kotlin?
Btw, issues are disabled on your fork. You still maintain it? There were no updates since sept 2019
Thanks

**Comment by lenguyenthanh** [comment]
Hi, I still maintain it!

I don't have any plan to convert the library to Kotlin. This is quite big project and it works well with all my projects (which are in Kotlin) so I don't see much benefit of converting this to Kotlin.

I just enabled issues tracking in my project. So if you have any things, please create new issue or pr.

Another thing is: This is also quite stable, so that's why there is no update since sept 2019.

Thanks
