### ISSUE TITLE
Missing drawable resources in library project

### ISSUE THREAD

**Issue by balysv** [palaima/DebugDrawer#11]
I assume they should be bundled [in the core library resources](https://github.com/palaima/DebugDrawer/tree/master/debugdrawer/src/main/res)

![screen shot 2015-06-30 at 5 38 44 pm](https://cloud.githubusercontent.com/assets/6113842/8436323/6075b3c6-1f4f-11e5-9c06-8cbde492287d.png)

Referenced [here](https://github.com/palaima/DebugDrawer/blob/master/debugdrawer/src/main/res/layout/debug_drawer_module_settings.xml#L29)

**Comment by palaima** [comment]
released v0.3.1 with resources added
