### ISSUE TITLE
Repository still active?

### ISSUE THREAD

**Issue by vanniktech** [palaima/DebugDrawer#15]
Hey are you still maintaining the repository?  If you'd like I could take care of it as a second maintainer.

**Comment by balysv** [comment]
Same here. This library is essentially what I wanted to make [here](https://github.com/lemonlabs/slidingdebugmenu) but never got around to finishing it. Would be happy to help.

**Comment by vanniktech** [comment]
@balysv 
Theoretically we could fork it and make our own version. I'd be happy to do that

**Comment by palaima** [comment]
Sorry guys for not responding
Currently i have a lot of work to do but i'll merge PRs as fast as possible
And again, thanks for contributing

**Comment by palaima** [comment]
Released DebugDrawer v0.3.1
Added missing resources, fixed NetworkController context memory leak, picasso indicator by current state, added LeakCanary to demo app

**Comment by vanniktech** [comment]
Thank you very much! In a few minutes you'll get another PR regarding outdated dependencies.
