### ISSUE TITLE
Dependency on api 15, should be lower

### ISSUE THREAD

**Issue by ebabel** [palaima/DebugDrawer#2]
Hi,
Thanks for making this lib! I cloned and changed api to 11 and there were no errors. If there are no reasons for api 15, would you lower it to 11?

Edit: Looks like Switch requires api 14. Use compat library?

**Comment by palaima** [comment]
Hi, thanks for suggestion.
Actually, Yes, Switch requires api 14 and also GridLayout requires api 14 wihich is used in Modules layouts.
So in my opinion library should target api 15

**Comment by ebabel** [comment]
How about using the compat option for both of those?

**Comment by palaima** [comment]
With next updated i have plans to lower min API, as you suggested with using compat library
