### ISSUE TITLE
Change your DrawerLayout's id please

### ISSUE THREAD

**Issue by Benjiko99** [palaima/DebugDrawer#38]
In **debugdrawer/src/main/res/layout/debug_drawer.xml** change the id of your DrawerLayout to something other than the **default** "drawer_layout" because if the application already has a navigation drawer with that same id it will create a lot of problems. Use something like "debug_drawer_layout" instead :)

**Comment by vanniktech** [comment]
+1 maybe even use a namespace for everything that is available for the end consumer of the library

**Comment by Sloy** [comment]
I wanted to suggest the same thing. Maybe use ‘dd_‘ as namespace for resource names.

**Comment by palaima** [comment]
Sure. Totally agree. Will roll up with next release! Thanks

**Comment by palaima** [comment]
Released `DebugDrawer 0.6.2`

Closing.
