### ISSUE TITLE
Expose DrawerLayout.setDrawerLockMode

### ISSUE THREAD

**Issue by aurae** [palaima/DebugDrawer#39]
I'd like to disable being able to open/close the debug drawer using swipe gestures, i.e. changing the lock mode of the underlying `DrawerLayout` to `LOCK_MODE_LOCKED_CLOSED`. Please consider exposing `setDrawerLockMode()` in `DebugDrawer`.

**Comment by palaima** [comment]
Released `DebugDrawer 0.6.2`

Closing.
