### ISSUE TITLE
Maybe you shouldn't be including dependencies like Timber, Picasso and Scalpel with the library, I rely on you to update them that way.

### ISSUE THREAD

**Issue by Benjiko99** [palaima/DebugDrawer#40]
Just tell me to add that one line of code into my build.gradle, its not gonna hurt the experience much.

**Comment by vanniktech** [comment]
+1 just use `provided` instead of `compile`

**Comment by anticafe** [comment]
Not sure if this article will be useful: http://johnpetitto.com/android-lib-dependency-management/

**Comment by palaima** [comment]
Released `DebugDrawer 0.6.2`

Closing.
