### ISSUE TITLE
Proguard Warning

### ISSUE THREAD

**Issue by simpleton** [palaima/DebugDrawer#41]
```
Warning: io.palaima.debugdrawer.scalpel.ScalpelModule: can't find referenced class com.jakewharton.scalpel.ScalpelFrameLayout
```

**Comment by vanniktech** [comment]
You have to manually include the Scalpel library. AFAIK starting with `0.6.2` the library does not ship with the libraries anymore, you need to depend on them. See #40

**Comment by simpleton** [comment]
@vanniktech Thank you.
