### ISSUE TITLE
Is it possible to hide DebugDrawer layout at runtime?

### ISSUE THREAD

**Issue by anticafe** [palaima/DebugDrawer#44]
I want to hide DebugDrawer at runtime - it means no UI of DebugDrawer, user cannot swipe from right to left to show it. Is it possible?

**Comment by palaima** [comment]
You mean that DebugDrawer should be available only for debug builds but not for release builds?

**Comment by anticafe** [comment]
Not related to debug or release build, but I want to hide DebugDrawer layout. Only show its UI by touch on secret region. For examle when send build to QA, I don't want to let them know there is DebugDrawer, however I can activate it anytime I need.

**Comment by palaima** [comment]
You can set `lock mode` via `debugDrawer.setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_CLOSED);`

and then call `debugDrawer.openDrawer();`

**Comment by palaima** [comment]
I'm closing this issue. If it is still necessary we could open it later.
