### ISSUE TITLE
AndroidRunTimeException SettingsModule

### ISSUE THREAD

**Issue by vanniktech** [palaima/DebugDrawer#59]
Getting:

> Fatal Exception: android.util.AndroidRuntimeException
Calling startActivity() from outside of an Activity context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?

on `SettingsModule#onClick:125`.

I'm using version 0.7.0. Also this is not reproduceable on every device. Happens on some Samsung and Sony devices. In any case the library should not crash.

**Comment by egor-n** [comment]
This issue should've been fixed by [this](https://github.com/palaima/DebugDrawer/commit/d082ca959eed1fcb350b6c67286a830334fa2227).

**Comment by vanniktech** [comment]
Thanks then I'll close this and wait for the next release.
