### ISSUE TITLE
Mobile network toggle view could be invisible for API 17 and above?

### ISSUE THREAD

**Issue by droidster** [palaima/DebugDrawer#61]
Mobile network toggle doesn't work on my device. I was checking the code and it's commented that it works only for api 16 and below. So, would it be better to not show it for api 17 and plus in the first place? Small issue but could save people using this library some time scratching their head. :) Please let me know if I could contribute.

**Comment by palaima** [comment]
Fix: 8e895ff6294cdddfcb965c44fbdd0dd156ee9659
