### ISSUE TITLE
Network delay/error adapters

### ISSUE THREAD

**Issue by kiwiandroiddev** [palaima/DebugDrawer#84]
I noticed this in the TODO section, and it sounds very useful for QA. As far as you're aware, has anyone started work on this? If not I might see if I can have a crack at it

Cheers

**Comment by Sloy** [comment]
I did it on my fork of the library, but I'm waiting for a response on #85 to decide what to do.
Here's how it looks like:
![screen shot 2017-08-25 at 13 34 11](https://user-images.githubusercontent.com/545251/29712436-1be3c3ee-899a-11e7-9421-7661bf68498a.png)

**Comment by palaima** [comment]
Thanks! I have included Network Quality and Logs Modules to project and added credits to you in readme.md
