### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by Sloy** [palaima/DebugDrawer#85]
Hi @palaima! I've started to implement the debug drawer in a few apps at my company, but needed some changes. I've sent a couple of PRs and have more things prepared. But I see there hasn't been any activity here for a few months.

Right now I have my own fork of the library, and I was wondering if it's worth sending PRs here or better officially diverge my fork and publish it as an independent library. I would also be ok becoming a maintainer of your repository, if you wish.

Could you please give us an update on your status with regard to the project?
Thanks!

**Comment by Sloy** [comment]
BTW here is my fork and another repo with some extra modules:

https://github.com/sloy/DebugDrawer/tree/fork

https://github.com/sloy/DebugDrawerModules

**Comment by palaima** [comment]
Finally i had time to come back to maintaining project. Soon 0.8.0 version will be released
